baseURL = "https://mattburgess.dev/"
title = "Matt Burgess"
copyright = "Copyright © {year} Matt Burgess. All Rights Reserved."
summaryLength = 5

# Novela settings
theme = "github.com/itsmattburgess/hugo-theme-spartan"

[params]
github_username = "itsmattburgess"
twitter_username = "itsmattburgess"
linkedin_username = "itsmattburgess"
intro = "A cloud-native solutions architect and software engineer. Specialises in modernizing applications into performant, observable and well architected platforms."

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 2

